better error handling

diff --git a/studip-sync b/studip-sync
--- a/studip-sync
+++ b/studip-sync
@@ -5,7 +5,7 @@ usage() {
     echo "Usage: $(basename "$0") [ OPTIONS... ] /path/to/studip/sync/dir"
     echo
     echo "OPTIONS:"
-    echo "  -v   enable verbose output"
+    echo "  -v   enable verbose output. Might print sensitive information!"
     echo "  -i   reads username and password from interactive prompt"
     echo "  -c   set alternative config directory"
     echo "  -h   display this help and exit"
@@ -61,7 +61,7 @@ fi
 
 if $verbose; then
     RSYNC_DBG_FLAG="-v"
-    CURL_DBG_FLAG=""
+    CURL_DBG_FLAG="-v"
 else
     CURL_DBG_FLAG="-s"
     RSYNC_DBG_FLAG=""
@@ -108,17 +108,27 @@ mkdir -p "$workdir"
 cd "$workdir" || exit 1
 
 sso_url=$(curl $CURL_DBG_FLAG \
-    -Lo tmp.html \
+    -fLo tmp.html \
     --cookie-jar cookies.txt \
     --write-out %{url_effective} \
     "https://studip.uni-passau.de/studip/index.php?again=yes&sso=shib")
 
+if [ $? -ne 0 ]; then
+    echo "An error occured while connecting to Stud.IP!"
+    exit 1
+fi
+
 curl $CURL_DBG_FLAG \
-    -Lo SAMLResponse \
+    -fLo SAMLResponse \
     --cookie-jar cookies.txt \
     --cookie cookies.txt \
     --data "j_username=$loginname&j_password=$password&_eventId_proceed=" \
     "$sso_url"
+
+if [ $? -ne 0 ]; then
+    echo "An error occured while authenticating to the Central Authentication Service!"
+    exit 1
+fi
 
 RelayState=$(grep --text RelayState SAMLResponse \
     | grep -Po 'value=".*?"' \
@@ -133,11 +143,16 @@ SAMLResponse=$(grep --text SAMLResponse SAMLResponse \
     | sed -e 's/=/%3D/g' -e 's/+/%2B/g')
 
 curl $CURL_DBG_FLAG \
-    -Lo tmp.html \
+    -fLo tmp.html \
     --cookie-jar cookies.txt \
     --cookie cookies.txt \
     --data "RelayState=$RelayState&SAMLResponse=$SAMLResponse"\
     "https://studip.uni-passau.de/Shibboleth.sso/SAML2/POST"
+
+if [ $? -ne 0 ]; then
+    echo "An error occured while authenticating to Stud.IP!"
+    exit 1
+fi
 
 curl_flags=""
 zip_files=( )
@@ -152,7 +167,12 @@ while read line; do
     fi
 done < <(cat $courses_conf_file)
 
-curl $CURL_DBG_FLAG -L --cookie cookies.txt $curl_flags
+curl $CURL_DBG_FLAG -fL --cookie cookies.txt $curl_flags
+
+if [ $? -ne 0 ]; then
+    echo "An error occured while downloading .zip archives!"
+    exit 1
+fi
 
 rm cookies.txt tmp.html SAMLResponse
 
